[ 2023-12-02 22:42:28,423 ] 224 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.10:8080
[ 2023-12-02 22:42:28,424 ] 224 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[ 2023-12-02 22:45:34,572 ] 224 werkzeug - INFO - 127.0.0.1 - - [02/Dec/2023 22:45:34] "GET / HTTP/1.1" 200 -
[ 2023-12-02 22:45:36,109 ] 224 werkzeug - INFO - 127.0.0.1 - - [02/Dec/2023 22:45:36] "HEAD / HTTP/1.1" 200 -
[ 2023-12-02 22:45:36,288 ] 224 werkzeug - INFO - 127.0.0.1 - - [02/Dec/2023 22:45:36] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[ 2023-12-02 22:45:36,494 ] 224 werkzeug - INFO - 127.0.0.1 - - [02/Dec/2023 22:45:36] "GET / HTTP/1.1" 200 -
[ 2023-12-02 22:45:37,017 ] 224 werkzeug - INFO - 127.0.0.1 - - [02/Dec/2023 22:45:37] "HEAD / HTTP/1.1" 200 -
[ 2023-12-02 22:45:38,461 ] 224 werkzeug - INFO - 127.0.0.1 - - [02/Dec/2023 22:45:38] "GET / HTTP/1.1" 200 -
[ 2023-12-02 22:45:38,942 ] 224 werkzeug - INFO - 127.0.0.1 - - [02/Dec/2023 22:45:38] "HEAD / HTTP/1.1" 200 -
[ 2023-12-02 22:45:42,387 ] 224 werkzeug - INFO - 127.0.0.1 - - [02/Dec/2023 22:45:42] "GET / HTTP/1.1" 200 -
[ 2023-12-02 22:45:43,017 ] 224 werkzeug - INFO - 127.0.0.1 - - [02/Dec/2023 22:45:43] "HEAD / HTTP/1.1" 200 -
[ 2023-12-03 09:55:48,077 ] 224 werkzeug - INFO - 127.0.0.1 - - [03/Dec/2023 09:55:48] "GET /predictdata HTTP/1.1" 200 -
[ 2023-12-03 09:55:49,914 ] 1741 app - ERROR - Exception on /predictdata [HEAD]
Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AWS-CI-CD-Projects\app.py", line 30, in predict_datapoint
    reading_score=float(request.form.get('writing_score')),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
[ 2023-12-03 09:55:49,985 ] 224 werkzeug - INFO - 127.0.0.1 - - [03/Dec/2023 09:55:49] "[35m[1mHEAD /predictdata HTTP/1.1[0m" 500 -
[ 2023-12-03 09:56:57,020 ] 1741 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "C:\Users\hp\AWS-CI-CD-Projects\src\pipeline\predict_pipeline.py", line 18, in predict
    data_scaled=preprocessor.transform(features)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\sklearn\utils\_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\sklearn\compose\_column_transformer.py", line 816, in transform
    Xs = self._fit_transform(
         ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\sklearn\compose\_column_transformer.py", line 670, in _fit_transform
    return Parallel(n_jobs=self.n_jobs)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\sklearn\utils\parallel.py", line 65, in __call__
    return super().__call__(iterable_with_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\joblib\parallel.py", line 1088, in __call__
    while self.dispatch_one_batch(iterator):
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\joblib\parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\hp\anaconda3\Lib\site-packages\joblib\parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\joblib\_parallel_backends.py", line 597, in __init__
    self.results = batch()
                   ^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\joblib\parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\joblib\parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\sklearn\utils\parallel.py", line 127, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\sklearn\pipeline.py", line 933, in _transform_one
    res = transformer.transform(X)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\sklearn\pipeline.py", line 689, in transform
    Xt = transform.transform(Xt)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\sklearn\utils\_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py", line 1025, in transform
    if self._drop_idx_after_grouping is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OneHotEncoder' object has no attribute '_drop_idx_after_grouping'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AWS-CI-CD-Projects\app.py", line 37, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AWS-CI-CD-Projects\src\pipeline\predict_pipeline.py", line 23, in predict
    raise CustomException(e,sys)
src.exception.CustomException: Error occured in python script name [C:\Users\hp\AWS-CI-CD-Projects\src\pipeline\predict_pipeline.py] line number [18] error message['OneHotEncoder' object has no attribute '_drop_idx_after_grouping']
[ 2023-12-03 09:56:57,056 ] 224 werkzeug - INFO - 127.0.0.1 - - [03/Dec/2023 09:56:57] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
[ 2023-12-03 09:56:57,988 ] 1741 app - ERROR - Exception on /predictdata [HEAD]
Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AWS-CI-CD-Projects\app.py", line 30, in predict_datapoint
    reading_score=float(request.form.get('writing_score')),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
[ 2023-12-03 09:56:57,994 ] 224 werkzeug - INFO - 127.0.0.1 - - [03/Dec/2023 09:56:57] "[35m[1mHEAD /predictdata HTTP/1.1[0m" 500 -
[ 2023-12-03 10:06:49,771 ] 224 werkzeug - INFO - 127.0.0.1 - - [03/Dec/2023 10:06:49] "GET / HTTP/1.1" 200 -
[ 2023-12-03 10:06:50,947 ] 224 werkzeug - INFO - 127.0.0.1 - - [03/Dec/2023 10:06:50] "HEAD / HTTP/1.1" 200 -
[ 2023-12-03 10:07:00,237 ] 224 werkzeug - INFO - 127.0.0.1 - - [03/Dec/2023 10:07:00] "GET /predictdata HTTP/1.1" 200 -
[ 2023-12-03 10:07:00,761 ] 1741 app - ERROR - Exception on /predictdata [HEAD]
Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AWS-CI-CD-Projects\app.py", line 30, in predict_datapoint
    reading_score=float(request.form.get('writing_score')),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
[ 2023-12-03 10:07:00,808 ] 224 werkzeug - INFO - 127.0.0.1 - - [03/Dec/2023 10:07:00] "[35m[1mHEAD /predictdata HTTP/1.1[0m" 500 -
[ 2023-12-03 10:07:30,731 ] 1741 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "C:\Users\hp\AWS-CI-CD-Projects\src\pipeline\predict_pipeline.py", line 18, in predict
    data_scaled=preprocessor.transform(features)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\sklearn\utils\_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\sklearn\compose\_column_transformer.py", line 816, in transform
    Xs = self._fit_transform(
         ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\sklearn\compose\_column_transformer.py", line 670, in _fit_transform
    return Parallel(n_jobs=self.n_jobs)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\sklearn\utils\parallel.py", line 65, in __call__
    return super().__call__(iterable_with_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\joblib\parallel.py", line 1088, in __call__
    while self.dispatch_one_batch(iterator):
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\joblib\parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\hp\anaconda3\Lib\site-packages\joblib\parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\joblib\_parallel_backends.py", line 597, in __init__
    self.results = batch()
                   ^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\joblib\parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\joblib\parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\sklearn\utils\parallel.py", line 127, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\sklearn\pipeline.py", line 933, in _transform_one
    res = transformer.transform(X)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\sklearn\pipeline.py", line 689, in transform
    Xt = transform.transform(Xt)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\sklearn\utils\_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py", line 1025, in transform
    if self._drop_idx_after_grouping is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OneHotEncoder' object has no attribute '_drop_idx_after_grouping'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AWS-CI-CD-Projects\app.py", line 37, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AWS-CI-CD-Projects\src\pipeline\predict_pipeline.py", line 23, in predict
    raise CustomException(e,sys)
src.exception.CustomException: Error occured in python script name [C:\Users\hp\AWS-CI-CD-Projects\src\pipeline\predict_pipeline.py] line number [18] error message['OneHotEncoder' object has no attribute '_drop_idx_after_grouping']
[ 2023-12-03 10:07:30,746 ] 224 werkzeug - INFO - 127.0.0.1 - - [03/Dec/2023 10:07:30] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
[ 2023-12-03 10:07:31,298 ] 1741 app - ERROR - Exception on /predictdata [HEAD]
Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AWS-CI-CD-Projects\app.py", line 30, in predict_datapoint
    reading_score=float(request.form.get('writing_score')),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
[ 2023-12-03 10:07:31,301 ] 224 werkzeug - INFO - 127.0.0.1 - - [03/Dec/2023 10:07:31] "[35m[1mHEAD /predictdata HTTP/1.1[0m" 500 -
[ 2023-12-03 10:08:48,847 ] 224 werkzeug - INFO - 127.0.0.1 - - [03/Dec/2023 10:08:48] "[31m[1mPOST / HTTP/1.1[0m" 405 -
[ 2023-12-03 10:08:56,625 ] 224 werkzeug - INFO - 127.0.0.1 - - [03/Dec/2023 10:08:56] "[31m[1mPOST / HTTP/1.1[0m" 405 -
[ 2023-12-03 10:09:08,883 ] 1741 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AWS-CI-CD-Projects\app.py", line 30, in predict_datapoint
    reading_score=float(request.form.get('writing_score')),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
[ 2023-12-03 10:09:08,901 ] 224 werkzeug - INFO - 127.0.0.1 - - [03/Dec/2023 10:09:08] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
[ 2023-12-03 10:09:11,390 ] 1741 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AWS-CI-CD-Projects\app.py", line 30, in predict_datapoint
    reading_score=float(request.form.get('writing_score')),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
[ 2023-12-03 10:09:11,471 ] 224 werkzeug - INFO - 127.0.0.1 - - [03/Dec/2023 10:09:11] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
[ 2023-12-03 10:09:44,074 ] 1741 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AWS-CI-CD-Projects\app.py", line 30, in predict_datapoint
    reading_score=float(request.form.get('writing_score')),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
[ 2023-12-03 10:09:44,076 ] 224 werkzeug - INFO - 127.0.0.1 - - [03/Dec/2023 10:09:44] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
